language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: JxGhIxsVGrxfGORN6dMIIAO8wEjP2HEvO+v+4SBwBCZofA3N3yv8rYRP7RAnEg/Tvt1NLDrvNThnDKGEBx/lR2apL6uJIoEOqLtvebe4Tn630W429g2FRXvNwdtWWdxqZdbAIuaV2GC0YaMhCSIEHi20vxvexQqXmPkIA9aS5MoThGWtp1DoaDTDXw5JJZNTgkcuoQy/kSOZuWcVVOBZ/petoahRiNbmnmtlhucrj23c4l4qKr/8lQmzOc4hg8poPb1o4i4tU+h/U7/sJB+9ad7epoyC20OQ+cfDI1KmfGKufObkthVlmX5ktN2Q/GwCjGsaSDrOX4kwoa+7E6h+uwD9BEUHIJkQcK/b8uZPT6z2yogxJzKZPPRMv3fU0dFS/oJXPbtNHx3v5yYuqzqQWlbrQE44Y+rwBnF5rnu/iA2/Dsaeg18Bs5iSnJKaW01cMxH6qalDun99lQ+EBV5HiqofrGSktOQmg50LyIfkEXfrKzfJIjv81HdYzdXTmtCmMqS2frmnJYXqx616s3CI/6gs+TMgnWCuiJtnT+X+3dlaZAqk+ZSSUQ8lLshLn4vYqjxIKPXO6FcvmPbQab52e+Q5meGC0H7WVkxR6lpGSayODl200lR+18+wSFZ+eQRa5WU1BTzujEObPSIYhNt2j/7Y2vLcnWxrkP5MyYjZRtk=
  - secure: EV7cvdgcQ99l/nScbhYjZMLo8IJRatuGwEvn2cH7N0yDzBc9dgeMwqDIfvLvqS0TxFyT0ZO3KpFuS6fwdEN39Q/78nyICfz3Wk+KiWJNkrPs29J8tJI69V390wg2VsZRsml56J3ibZYaS0yyf28RDp2RXL3/BsDmDKtSOZQaAfCr9TFeGc2n4qg9T4Ro3AiEpZJzMi7YROVA/i5zkwF5WyCsHKFih26YB9ouveeBL68V4FlmalzMJH0115mZ2x8uJZ9bbHrtWb24RqMgysDyKZZGaMm9YMdkhpYezmjeC4k9vA6rTSTbL09hpa05BTniaUjsRAbBky0Us4C4qSxip29meVU2gUqL69nS6czKJi9SV9xM3PpjFEoF7OX9d83jBjZyddFEL11EMI02gDCdz01I479JPAT6AVgexFSN1tUMXOVdAViMsl6AOI9QiTa+mY3hQyyKC8iEvZJAvkdPnuMSbvrt42dnVGkcW8gj1gBMmHnO/8eBqh9ogyzbbYEZmo/akFy8o8Ppwx32UBGuwjAmFFeq663wPdvEbuYZY6xVl8wVlUyLewc9y32dEdksv+sQGkFKi3rzKyTQUwYynMLegUgKPmQTEF5QkNwiI8Il1H7B7XlYNN6MuTnitO38RfweH9aQcAnZKhtZuUTkauKScCa5CLtIJJ6GLVaEkio=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: HT+Ql1b9iviluAmbSrnbQ9QkLgJs6tej6+jEqoJ3HGYDczl02pYIhin3w9rMo8DFhflv1q1Wx6vcZyZtS4VxHDt3GMVzGg4XZGDXLOR1Iwx3ZDrGSDT5ehwi9qImsRDXQKxgCfU7QPo9PjCGMXK0ELX3OBpLdTrUvodfOnRx/RQ4IX5fVl6tN2yN4hCOXqCycmsgsPx01inAJ9dIyEPLBBeAIfa+WHz4OFWPRzmJx/NeQdaj5VygSHZuSda9I5d6FR4UATiCHIWQZqNBNpO9MKf4Hz9yh2zRdfO+JO33aPEv6CJkRDdvK1I8puZRBZOBKfeYB1t31lJMtuqIr9NU2VgmPKUCQV8N+Bdyf/XopkF6OCL5ylLTiW3l51kTDg8XxdurFwE1OoRVKll7/4YF1jsqKvoAH7mv7kBAyMu+ERPjqQQ4qg9mIQ5j7PXTjmFDbt/MjMIkBTCclp5OdvZUuHx7VWvbe2LQhzkH/FQ7Gs11z8K0qxgJT40hCMW1n6TMTdgqG7VvJk35Fyg2r+dasp4YXb7fV7wsSvbo9K8MvFHYNPDTYtO+shDIwklRbLRScnoqLAuynvdk9zFeysoXYVqP36LM+aCSyPGcKCrB0NvLbwehTAarmG7tFCsEW8Y9l9cH3SwLM4sNQddzSeK9OvZP0pdGKBNqqRLe64csxd4=
  on:
    repo: plepers/nanogl-camera
    branch: master
